source "https://rubygems.org"
#
#     bundle install
#     bundle exec jekyll serve
#

gem "jekyll", "~> 4.3.2"

group :jekyll_plugins do
  # for RSS feed
  gem 'jekyll-feed', '~> 0.13'
  # Sitemap
  gem 'jekyll-sitemap', '~> 1.4.0'
  # For Easier Links
  gem 'jekyll-compose', '~> 0.12.0'
end
